#!/bin/bash
export PATH=/exports/eddie/scratch/s1749179/anaconda/envs/chipseq/bin:$PATH
cat /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/SOX2_H3K27AC_overlap_peaks.txt | while read line || [ -n "$line" ];
do
	SAMPLE_NAME=`printf $line | cut -f 1`
	echo $SAMPLE_NAME
	bedtools getfasta -fi /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/reference/hg38.fa -bed /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_merged.bed > /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_merged.fasta
	bedtools getfasta -fi /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/reference/hg38.fa -bed /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_merged_intergenic.bed > /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_merged_intergenic.fasta
	bedtools getfasta -fi /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/reference/hg38.fa -bed /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_merged_promoter.bed > /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_merged_promoter.fasta
	bedtools getfasta -fi /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/reference/hg38.fa -bed /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_merged_intragenic.bed > /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_merged_intragenic.fasta
	bedtools getfasta -fi /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/reference/hg38.fa -bed /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_SOXregion.bed > /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_SOXregion.fasta
	bedtools getfasta -fi /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/reference/hg38.fa -bed /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_SOXregion_intergenic.bed > /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_SOXregion_intergenic.fasta
	bedtools getfasta -fi /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/reference/hg38.fa -bed /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_SOXregion_promoter.bed > /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_SOXregion_promoter.fasta
	bedtools getfasta -fi /exports/eddie/scratch/s1749179/sox_cancer_enhancers/resources/reference/hg38.fa -bed /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_SOXregion_intragenic.bed > /exports/eddie/scratch/s1749179/sox_cancer_enhancers/processed_data/intersections/${SAMPLE_NAME}_SOX2_H3K27AC_overlaps_SOXregion_intragenic.fasta
done
